from __future__ import annotations

from typing import Optional

class JEInternBaseClass:
    __instance_policy__: str
    __instance_limit__: Optional[int]
    __recursive__: bool
    def __init__(self) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def to_dict(self) -> dict: ...
    def debug(self, *, is_colored: bool = False, max_depth: int = -1, brached_recursive: bool = False, prefix: str = "", is_last: bool = True, is_root: bool = True, show_root: bool = True) -> str: ...
    def dump(self, *, prefix: str = "", is_last: bool = True, is_root: bool = True): ...
