from __future__ import annotations

from types import NoneType

from jarengine.resources.texture import JETexture
from jarengine.resources.font import JEFont
from jarengine.resources.music import JEMusic
from jarengine.resources.sound import JESound
from jarengine.interns.low_classes import JEInternGraphic
from jarengine.systems.container import JEContainer
from jarengine.entities.entity import JEEntity

class JEInternEmptyComponent:
    def __init__(self, owner: JEEntity): ...
    def __call__(self) -> NoneType: ...
    def __bool__(self) -> bool: ...
    def copy(self, new_owner: JEEntity) -> JEInternEmptyComponent: ...

class JEInternResources:
    def __init__(self): ...
    @property
    def texture(self) -> JEContainer[JETexture]: ...
    @property
    def animations(self) -> JEContainer[JEInternGraphic]: ...
    @property
    def font(self) -> JEContainer[JEFont]: ...
    @property
    def music(self) -> JEContainer[JEMusic]: ...
    @property
    def sound(self) -> JEContainer[JESound]: ...

class JEInternWindowSettings:
    def __init__(self, size: tuple[int, int], flags: int,fps: int, depth: int, display: int, vsync: int, title: str): ...
    @property
    def size(self) -> tuple[int, int]: ...
    @size.setter
    def size(self, size: tuple[int, int]): ...
    @property
    def flags(self) -> int: ...
    @property
    def fps(self) -> int: ...
    @fps.setter
    def fps(self, fps: int): ...
    @property
    def depth(self) -> int: ...
    @property
    def display(self) -> int: ...
    @property
    def vsync(self) -> int: ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, title: str): ...
    def __deepcopy__(self, memo): ...
