from __future__ import annotations

from jarengine.interns.low_classes import JEInternGraphic
from jarengine.entities.entity import JEEntity
from jarengine.games.game import JEGame
from jarengine.games.window import JEWindow
from jarengine.interns.base_classe import JEInternBaseClass
from jarengine.systems.container import JEContainer

class JEInternOwnership(JEInternBaseClass):
    def __init__(self): ...
    @property
    def parents(self) -> JEContainer[JEInternBaseClass]: ...
    def add_parent(self, parent: JEInternBaseClass): ...
    @property
    def children(self) -> JEContainer[JEInternBaseClass]: ...
    def add_child(self, child: JEInternBaseClass): ...

class JEInternEntityComponent(JEInternGraphic, JEInternOwnership):
    def __init__(self, owner: JEEntity, _type: type): ...
    def __call__(self): ...

class JEInternSystems(JEInternOwnership):
    cache: list[JEEntity]
    def __init__(self, owner: JEGame): ...
    def refresh(self): ...
    def sort_cache(self): ...
    def accepts(self, components: JEContainer[JEInternEntityComponent]): ...
    @staticmethod
    def update(window: JEWindow, entity: JEEntity, entities: JEContainer[JEEntity], dt: float): ...
