from __future__ import annotations

from jarengine.interns.low_classes import JEInternGraphic
from jarengine.entities.entity import JEEntity
from jarengine.games.game import JEGame
from jarengine.games.window import JEWindow
from jarengine.interns.base_classe import JEInternBaseClass
from jarengine.systems.container import JEContainer

class JEInternOwnership(JEInternBaseClass):
    def __init__(self) -> None: ...
    @property
    def parents(self) -> JEContainer[JEInternBaseClass]: ...
    def add_parent(self, parent: JEInternBaseClass) -> None: ...
    @property
    def children(self) -> JEContainer[JEInternBaseClass]: ...
    def add_child(self, child: JEInternBaseClass) -> None: ...

class JEInternEntityComponent(JEInternGraphic, JEInternOwnership):
    def __init__(self, owner: JEEntity, _type: type) -> None: ...
    def __call__(self): ...

class JEInternSystems(JEInternOwnership):
    cache: list[JEEntity]
    def __init__(self, owner: JEGame): ...
    def refresh(self) -> None: ...
    def sort_cache(self) -> None: ...
    def accepts(self, components: JEContainer[JEInternEntityComponent]): ...
    @staticmethod
    def update(window: JEWindow, entity: JEEntity, entities: JEContainer[JEEntity], dt: float) -> None: ...

class JEInternTransform(JEInternBaseClass):
    def __add__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __sub__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __mul__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __rmul__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __truediv__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __neg__(self) -> JEInternTransform: ...
    def __eq__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __iadd__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __isub__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __imul__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __itruediv__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __len__(self) -> float: ...
    def length(self) -> float: ...
    def normalize(self) -> float: ...
    def dot(self, other: JEInternTransform) -> float: ...
    def distance(self, other: JEInternTransform) -> float: ...
    def copy(self) -> JEInternTransform: ...
    def to_list(self) -> list: ...
    def __repr__(self) -> str: ...
