from __future__ import annotations

from jarengine.interns.base_classe import JEInternBaseClass
from jarengine.systems.bool import JEBool

class JEInternGraphic(JEInternBaseClass):
    def __init__(self, name: str) -> None: ...
    def destroy(self) -> None: ...
    @property
    def is_alive(self) -> JEBool: ...

class JEInternGraphicalObject(JEInternGraphic):
    def __init__(self, name: str) -> None: ...
    def update(self, dt: float) -> None: ...
    def mark_dirty(self) -> None: ...
    def clear_dirty(self) -> None: ...
    @property
    def is_dirty(self) -> JEBool: ...

class JEInternResource(JEInternGraphic):
    def __init__(self, name: str, path: str) -> None: ...
    @property
    def path(self) -> str: ...
