from __future__ import annotations

from jarengine.interns.base_classe import JEInternBaseClass
from jarengine.systems.bool import JEBool

class JEInternGraphic(JEInternBaseClass):
    def __init__(self, name: str): ...
    def destroy(self): ...
    @property
    def is_alive(self) -> JEBool: ...

class JEInternGraphicalObject(JEInternGraphic):
    def __init__(self, name: str): ...
    def update(self, dt: float): ...
    def mark_dirty(self): ...
    def clear_dirty(self): ...
    @property
    def is_dirty(self) -> JEBool: ...

class JEInternResource(JEInternGraphic):
    def __init__(self, name: str, path: str): ...
    @property
    def path(self) -> str: ...
