from __future__ import annotations

from jarengine.systems.bool import JEBool

class JEInternGraphic:
    def __init__(self, name: str) -> None: ...
    def destroy(self) -> None: ...
    @property
    def is_alive(self) -> JEBool: ...

class JEInternGraphicalObject:
    def __init__(self, name: str) -> None: ...
    def update(self, dt: float) -> None: ...
    def mark_dirty(self) -> None: ...
    def clear_dirty(self) -> None: ...
    @property
    def is_dirty(self) -> JEBool: ...

class JEInternResource:
    def __init__(self, name: str, path: str) -> None: ...
    @property
    def path(self) -> JEBool: ...
