from __future__ import annotations

from typing import Callable, Self

from jarengine.games.game import JEGame
from jarengine.events.manager import JEEvent

class JEEventCode:
    def __init__(self, event: int | None) -> None: ...
    def __int__(self) -> int: ...
    @property
    def name(self) -> str: ...
    def __or__(self, other: JEEventCode) -> JEEventCodeGroup: ...
    def __eq__(self, other: JEEventCode) -> bool: ...
    def __hash__(self) -> int: ...

class JEEventCodeGroup:
    def __init__(self, events: list[JEEventCode]): ...
    def __or__(self, other: JEEventCode | JEEventCodeGroup) -> JEEventCodeGroup: ...
    def __iter__(self): ...
    @property
    def events(self): ...

class JEEventWatcher:
    def __init__(self, on: JEEventCode | list[JEEventCode] | JEEventCodeGroup, do: Callable[[JEGame, JEEvent], None]) -> None: ...
    def match(self, event: JEEvent) -> bool: ...
    def __call__(self, game: JEGame, event: JEEvent) -> None: ...
    @property
    def on(self) -> JEEventCodeGroup: ...
    @property
    def do(self) -> str: ...
