from __future__ import annotations

from typing import Callable, Self

from jarengine.events.event import JEEventCode
from jarengine.games.game import JEGame
from jarengine.events.manager import JEEvent
from jarengine.systems.bool import JEBool

class JEMouseCode:
    def __init__(self, mouse: int | None) -> None: ...
    def __int__(self) -> int: ...
    @property
    def name(self) -> str: ...
    def __or__(self, other: JEMouseCode) -> JEMouseCodeGroup: ...
    def __eq__(self, other: JEEventCode) -> bool: ...
    def __hash__(self) -> int: ...

class JEMouseCodeGroup:
    def __init__(self, mouses: list[JEMouseCode]) -> None: ...
    def __or__(self, other: JEMouseCode | JEMouseCodeGroup) -> JEMouseCodeGroup: ...
    def __iter__(self): ...
    @property
    def mouses(self): ...

class JEMouseWatcher:
    def __init__(self, on: JEMouseCode | list[JEMouseCode] | JEMouseCodeGroup, do: Callable[[JEGame, JEEvent], None], on_press: JEBool) -> None: ...
    def match(self, event: JEEvent) -> bool: ...
    def __call__(self, game: JEGame, event: JEEvent) -> None: ...
    @property
    def on(self) -> JEMouseCodeGroup: ...
    @property
    def params(self) -> JEEventCode: ...
    @property
    def do(self) -> str: ...
