from __future__ import annotations

from sources.entities.entity import JEEntity
from sources.systems.vector import JEVector2D

class JEPositionComponent:
    def __init__(self, owner: JEEntity, position: JEVector2D | tuple[float, float]) -> None: ...
    @property
    def position(self) -> JEVector2D: ...
    @position.setter
    def position(self, position: JEVector2D | tuple[float, float]) -> None: ...
    def __call__(self) -> JEVector2D: ...
    def copy(self, new_owner: JEEntity) -> JEPositionComponent: ...

class JEVelocityComponent:
    def __init__(self, owner: JEEntity, velocity: JEVector2D | tuple[float, float]) -> None: ...
    @property
    def velocity(self) -> JEVector2D: ...
    @velocity.setter
    def velocity(self, velocity: JEVector2D | tuple[float, float]) -> None: ...
    def __call__(self) -> JEVector2D: ...
    def copy(self, new_owner: JEEntity) -> JEVelocityComponent: ...

class JESizeComponent:
    def __init__(self, owner: JEEntity, size: JEVector2D | tuple[float, float]) -> None: ...
    @property
    def size(self) -> JEVector2D: ...
    @size.setter
    def size(self, size: JEVector2D | tuple[float, float]): ...
    def __call__(self) -> JEVector2D: ...
    def copy(self, new_owner: JEEntity) -> JESizeComponent: ...

class JERotationComponent:
    def __init__(self, owner: JEEntity, rotation: float) -> None: ...
    @property
    def rotation(self) -> float: ...
    @rotation.setter
    def rotation(self, rotation: float): ...
    def __call__(self) -> float: ...
    def copy(self, new_owner: JEEntity) -> JERotationComponent: ...
