"""
    JarEngine - Python Game Engine Wrapper (Pygame-based)

    JarEngine is a lightweight game framework built on top of Pygame
    that simplifies usage while providing higher-level abstractions for
    game development and prototyping.

    Version: jarengine-v0.1.0
    Author: Jarjarbin Studio
    Licence: GPL v3

    This engine is inspired by Pygame, modern game engine design patterns,
    and directly influenced by the architecture of NewCSFML.

    It is designed for educational purposes and small-to-medium game projects.

    It provides structured systems such as entity management, scene handling,
    render abstraction, and advanced modules like particle systems.

    WARNING:
        This is NOT Pygame itself.
        It is a custom abstraction layer built on top of Pygame.
"""

from __future__ import annotations

from sources.entities.entity import JEEntity
from sources.graphics.texture import JETexture
from sources.systems.color import JEColor
from sources.systems.bool import JEBool

class JETextureComponent:
    def __init__(self, owner: JEEntity, texture: JETexture) -> None: ...
    @property
    def texture(self) -> JETexture: ...
    @texture.setter
    def texture(self, texture: JETexture) -> None: ...
    def __call__(self) -> JETexture: ...
    def copy(self, new_owner: JEEntity) -> JETextureComponent: ...

class JEColorComponent:
    def __init__(self, owner: JEEntity, color: JEColor | tuple[int, int, int] | tuple[int, int, int, int]) -> None: ...
    @property
    def color(self) -> JEColor: ...
    @color.setter
    def color(self, color: JEColor | tuple[int, int, int] | tuple[int, int, int, int]): ...
    def __call__(self) -> JEColor: ...
    def copy(self, new_owner: JEEntity) -> JEColorComponent: ...

class JEVisibilityComponent:
    def __init__(self, owner: JEEntity, visibility: JEBool): ...
    @property
    def visibility(self: JEBool): ...
    @visibility.setter
    def visibility(self, visibility: JEBool): ...
    def __call__(self: JEBool): ...
    def copy(self, new_owner: JEEntity) -> JEVisibilityComponent: ...

class JELayerComponent:
    def __init__(self, owner: JEEntity, layer: int): ...
    @property
    def layer(self: int): ...
    @layer.setter
    def layer(self, layer: int): ...
    def __call__(self: int): ...
    def copy(self, new_owner: JEEntity) -> JELayerComponent: ...

class JEFlipComponent:
    def __init__(self, owner: JEEntity, flip: tuple[JEBool, JEBool]): ...
    @property
    def flip(self) -> tuple[JEBool, JEBool]: ...
    @flip.setter
    def flip(self, flip: tuple[JEBool, JEBool]): ...
    def __call__(self: tuple[JEBool, JEBool]): ...
    def copy(self, new_owner: JEEntity) -> JEFlipComponent: ...
