from __future__ import annotations

from sources.resources.font import JEFont
from sources.interns.high_classes import JEInternalEntityComponent
from sources.systems.container import JEContainer
from sources.systems.vector import JEVector2D
from sources.resources.texture import JETexture
from sources.systems.bool import JEBool
from sources.systems.color import JEColor


class JEEntity:
    def __init__(self, *, name: str) -> None: ...
    @property
    def components(self) -> JEContainer[JEInternalEntityComponent]: ...
    def add_component(self, component: JEInternalEntityComponent) -> None: ...
    def get(self, component: type) -> JEInternalEntityComponent: ...
    def copy(self) -> JEEntity: ...


    ### COMPONENTS ###
    ## Graphics ##
    # Font #
    def set_font(self, font: JEFont) -> None: ...
    def get_font(self) -> JEFont: ...

    # Text #
    def set_text(self, text: str) -> None: ...
    def get_text(self) -> str: ...

    # Texture #
    def set_texture(self, texture: JETexture) -> None: ...
    def get_texture(self) -> JETexture: ...

    # Color #
    def set_color(self, color: JEColor | tuple[int, int, int] | tuple[int, int, int, int]) -> None: ...
    def update_color(self, *, r: int, g: int, b: int, a: int) -> None: ...
    def get_color(self) -> JEColor | tuple[int, int, int] | tuple[int, int, int, int]: ...

    # Visibility #
    def set_visibility(self, visibility: JEBool) -> None: ...
    def get_visibility(self) -> JEBool: ...

    # Layer #
    def set_layer(self, mass: int) -> None: ...
    def update_layer(self, *, l: int) -> None: ...
    def get_layer(self) -> int: ...

    # Flip #
    def set_flip(self, flip: tuple[JEBool, JEBool]) -> None: ...
    def get_flip(self) -> tuple[JEBool, JEBool]: ...

    ## Physics ##
    # Acceleration #
    def set_acceleration(self, acceleration: JEVector2D | tuple[float, float]) -> None: ...
    def update_acceleration(self, *, x: float, y: float) -> None: ...
    def get_acceleration(self) -> JEVector2D: ...

    # Mass #
    def set_mass(self, mass: float) -> None: ...
    def update_mass(self, *, m: float) -> None: ...
    def get_mass(self) -> float: ...

    ## Transforms ##
    # Position #
    def set_position(self, position: JEVector2D | tuple[float, float]) -> None: ...
    def update_position(self, *, x: float, y: float) -> None: ...
    def get_position(self) -> JEVector2D: ...

    # Velocity #
    def set_velocity(self, velocity: JEVector2D | tuple[float, float]) -> None: ...
    def update_velocity(self, *, x: float, y: float) -> None: ...
    def get_velocity(self) -> JEVector2D: ...

    # Size #
    def set_size(self, size: JEVector2D | tuple[float, float]) -> None: ...
    def update_size(self, *, x: float, y: float) -> None: ...
    def get_size(self) -> JEVector2D: ...

    # Rotation #
    def set_rotation(self, rotation: float) -> None: ...
    def update_rotation(self, *, r: float) -> None: ...
    def get_rotation(self) -> float: ...
