from __future__ import annotations

from typing import Any

class JEInternClassBase:
    __instance_policy__ = "normal"
    __instance_limit__ = None
    __recursive__ = True
    def __init__(self) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def to_dict(self) -> dict: ...
    def debug(self, *, is_colored: bool, max_depth: int, brached_recursive: bool, prefix: str, is_last: bool, is_root: bool, show_root: bool) -> str: ...
    def dump(self, *, prefix: str, is_last: bool, is_root: bool, _attr_key: Any, _visited: set | None): ...
