from __future__ import annotations

from sources.entities.entity import JEEntity
from sources.games.game import JEGame
from sources.games.window import JEWindow
from sources.interns.base_classe import JEInternBaseClass
from sources.systems.container import JEContainer

class JEInternOwnership:
    def __init__(self) -> None: ...
    @property
    def parents(self) -> JEContainer[JEInternBaseClass]: ...
    def add_parent(self, parent: JEInternBaseClass) -> None: ...
    @property
    def children(self) -> JEContainer[JEInternBaseClass]: ...
    def add_child(self, child: JEInternBaseClass) -> None: ...

class JEInternEntityComponent:
    def __init__(self, owner: JEEntity, _type: type) -> None: ...
    def __call__(self): ...

class JEInternSystems:
    def __init__(self, owner: JEGame): ...
    def accepts(self, components: JEContainer[JEInternEntityComponent]): ...
    @staticmethod
    def update(window: JEWindow, entity: JEEntity, entities: JEContainer[JEEntity], dt: float) -> None: ...
