from __future__ import annotations

from sources.entities.entity import JEEntity
from sources.games.game import JEGame
from sources.games.window import JEWindow
from sources.interns.base_classe import JEInternClassBase
from sources.systems.container import JEContainer

class JEInternalOwnership:
    def __init__(self) -> None: ...
    @property
    def parents(self) -> JEContainer[JEInternClassBase]: ...
    def add_parent(self, parent: JEInternClassBase) -> None: ...
    @property
    def children(self) -> JEContainer[JEInternClassBase]: ...
    def add_child(self, child: JEInternClassBase) -> None: ...

class JEInternalEntityComponent:
    def __init__(self, owner: JEEntity, _type: type) -> None: ...
    def __call__(self): ...

class JEInternalRenderingSystems:
    def __init__(self, owner: JEGame): ...
    def accepts(self, components: JEContainer[JEInternalEntityComponent]): ...
    @staticmethod
    def update(window: JEWindow, entity: JEEntity, entities: JEContainer[JEEntity], dt: float) -> None: ...
