from __future__ import annotations

from jarengine.interns import PGExtern
from jarengine.systems.vector import JEVector2D

class JETexture:
    def __init__(self, name: str, path: str) -> None: ...
    @property
    def surface(self) -> PGExtern.Surface: ...
    @property
    def path(self) -> str: ...
    @property
    def size(self) -> JEVector2D: ...
