from __future__ import annotations

from typing import Any

from jarengine.interns.base_classe import JEInternBaseClass

class JEBool(JEInternBaseClass):
    def __init__(self, value: Any): ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    @property
    def data(self) -> bool: ...
