from __future__ import annotations

from jarengine.interns.base_classe import JEInternBaseClass

class JEClock(JEInternBaseClass):
    def __init__(self, fps: int = 60) -> None: ...
    def update(self) -> None: ...
    @property
    def dt(self) -> float: ...
    @property
    def target_fps(self) -> int: ...
    @target_fps.setter
    def target_fps(self, value: int) -> None: ...
    @property
    def fps(self) -> float: ...
    def __float__(self) -> float: ...
