from __future__ import annotations

from typing import Iterator

from jarengine.interns.base_classe import JEInternBaseClass

class JEColor(JEInternBaseClass):
    def __init__(self, r: int = 0, g: int = 0, b: int = 0, a: int = 255): ...
    @property
    def r(self) -> int: ...
    @r.setter
    def r(self, r: int): ...
    @property
    def g(self) -> int: ...
    @g.setter
    def g(self, g: int): ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, b: int): ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, a: int): ...
    @property
    def rgb(self) -> tuple[int, int, int]: ...
    @property
    def rgba(self) -> tuple[int, int, int, int]: ...
    def __iter__(self) -> Iterator[float]: ...
