from __future__ import annotations

from typing import TypeVar, Optional, Iterator, Any, Generic

from jarengine.interns.base_classe import JEInternBaseClass
from jarengine.systems.bool import JEBool

T = TypeVar("T", bound=JEInternBaseClass)

class JEContainer(Generic[T], JEInternBaseClass):
    def __init__(self, allowed_type: type, allow_subclass: JEBool = JEBool(0)): ...
    def __setitem__(self, obj: T): ...
    def add(self, obj: T): ...
    def __getitem__(self, value: str | T) -> T: ...
    def get(self, *, name: Optional[str] = None, jeid: Optional[str] = None, instance: Optional[T] = None, _type: type = None, default: Any = NotImplemented) -> T: ...
    def rm(self, *, name: Optional[str] = None, jeid: Optional[str] = None, instance: Optional[T] = None, _type: type = None) -> T: ...
    def clear(self): ...
    def __iter__(self) -> Iterator[T]: ...
    @property
    def data(self) -> T: ...
