from __future__ import annotations

from typing import Any, Callable, TypeVar, Type, Iterator, Generic

from jarengine.interns.base_classe import JEInternBaseClass

T: TypeVar = TypeVar("T")

class JEImmutable(Generic[T], JEInternBaseClass):
    def __init__(self, value: T): ...
    @property
    def data(self) -> T: ...
    @property
    def frozen(self) -> Any: ...
    @property
    def type(self) -> Type[T]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: Any) -> Any: ...
    def __contains__(self, item: Any) -> bool: ...
    def __bool__(self) -> bool: ...
    def __reversed__(self) -> Iterator[Any]: ...
    def map(self, func: Callable[[Any], Any]) -> list[Any]: ...
    def filter(self, func: Callable[[Any], bool]) -> list[Any]: ...
    def any(self) -> bool: ...
    def all(self) -> bool: ...
    def count(self, value: Any) -> int: ...
    def index(self, value: Any) -> int: ...
    def keys(self): ...
    def values(self): ...
    def items(self): ...
    def get(self, key: Any, default: Any = None) -> Any: ...
    def to_list(self) -> list[Any]: ...
    def to_dict(self) -> dict[Any, Any]: ...
    def clone(self) -> JEImmutable[T]: ...
    def __eq__(self, other: object) -> bool: ...
