from __future__ import annotations

from jarengine.interns.base_classe import JEInternBaseClass

class JETransform(JEInternBaseClass):
    def __add__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __sub__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __mul__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __rmul__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __truediv__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __neg__(self) -> JEInternTransform: ...
    def __eq__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __iadd__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __isub__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __imul__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __itruediv__(self, other: JEInternTransform) -> JEInternTransform: ...
    def __len__(self) -> float: ...
    def length(self) -> float: ...
    def normalize(self) -> float: ...
    def dot(self, other: JEInternTransform) -> float: ...
    def distance(self, other: JEInternTransform) -> float: ...
    def copy(self) -> JEInternTransform: ...
    def to_list(self) -> list: ...
    def __repr__(self) -> str: ...
