from __future__ import annotations

from typing import Iterator

class JEVector2D:
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, x: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, y: float) -> None: ...
    def __iter__(self): ...

class JEVector3D:
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, x: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, y: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, z: float) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
