from __future__ import annotations

from typing import Iterator

from jarengine.interns.high_classes import JEInternTransform

class JEVector2D(JEInternTransform):
    def __init__(self, x: float = 0.0, y: float = 0.0):
        """
            JEVector2D

            Parameters:
                x (float) = 0.0: x coordinate
                y (float) = 0.0: y coordinate
        """
        ...
    @property
    def x(self) -> float:...
    @x.setter
    def x(self, x: float): ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, y: float): ...
    def __iter__(self) -> Iterator[float]: ...

class JEVector3D(JEInternTransform):
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0): ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, x: float): ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, y: float): ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, z: float): ...
    def __iter__(self) -> Iterator[float]: ...
