from __future__ import annotations

class JEVersion:
    def __init__(self, major: int, minor: int, patch: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def major(self) -> int: ...
    @property
    def minor(self) -> int: ...
    @property
    def patch(self) -> int: ...
