from __future__ import annotations

from jarengine.interns.base_classe import JEInternBaseClass
from jarengine.interns import PGExtern

class JEVersion(PGExtern.version.SoftwareVersion, JEInternBaseClass):
    def __init__(self, major: int, minor: int, patch: int): ...
    def __str__(self) -> str: ...
    @property
    def major(self) -> int: ...
    @property
    def minor(self) -> int: ...
    @property
    def patch(self) -> int: ...
