from __future__ import annotations

from sources.games.window import JEWindow
from sources.games.input import JEInput
from sources.events.manager import JEEventHandler
from sources.events.keyboard import JEKeyCode
from sources.events.mouse import JEMouseCode
from sources.entities.entity import JEEntity
from sources.systems.container import JEContainer
from sources.interns.high_classes import JEInternalRenderingSystems
from sources.interns.final_classes import JEInternRessources
from sources.systems.bool import JEBool
from sources.systems.clock import JEClock

class JEGame:
    def __init__(self, *, use_clock: bool, use_input: bool) -> None: ...
    def set_window(self, window: JEWindow): ...
    @property
    def wdw(self) -> JEWindow: ...
    @property
    def input(self) -> JEInput: ...
    def is_key_down(self, key: JEKeyCode) -> bool: ...
    def is_mouse_down(self, button: JEMouseCode) -> bool: ...
    @property
    def clock(self) -> JEClock: ...
    @property
    def dt(self) -> float: ...
    @property
    def event(self) -> JEEventHandler: ...
    @property
    def is_open(self) -> JEBool: ...
    @property
    def ressource(self) -> JEInternRessources: ...
    @property
    def entities(self) -> JEContainer[JEEntity]: ...
    def close(self) -> None: ...
    def add_system(self, system: JEInternalRenderingSystems) -> None: ...
    @property
    def systems(self) -> JEContainer[JEInternalRenderingSystems]: ...
    def update(self) -> None: ...
    def display(self) -> None: ...
