from __future__ import annotations

from sources.events.keyboard import JEKeyCode
from sources.events.mouse import JEMouseCode

class JEInput:
    def __init__(self) -> None: ...
    def update(self) -> None: ...
    def is_key_down(self, key: JEKeyCode) -> bool: ...
    def is_mouse_down(self, button: JEMouseCode) -> bool: ...
    def mouse_pos(self) -> tuple[int, int]: ...
    def __call__(self, code: JEKeyCode | JEMouseCode) -> bool: ...
