from __future__ import annotations

from sources.interns.high_classes import JEInternalEntityComponent
from sources.entities.entity import JEEntity
from sources.systems.container import JEContainer
from sources.games.window import JEWindow
from sources.games.game import JEGame
from sources.systems.bool import JEBool

class JEMovementSystem:
    def __init__(self, owner: JEGame): ...
    def accepts(self, components:  JEContainer[JEInternalEntityComponent]) -> JEBool: ...
    def update(self, window: JEWindow, entity: JEEntity, entities: JEContainer[JEEntity], dt: float) -> None: ...

class JERenderSystem:
    def __init__(self, owner: JEGame): ...
    def accepts(self, components:  JEContainer[JEInternalEntityComponent]) -> JEBool: ...
    def update(self, window: JEWindow, entity: JEEntity, entities: JEContainer[JEEntity], dt: float) -> None: ...

class JEAccelerationSystem:
    def __init__(self, owner: JEGame): ...
    def accepts(self, components:  JEContainer[JEInternalEntityComponent]) -> JEBool: ...
    def update(self, window: JEWindow, entity: JEEntity, entities: JEContainer[JEEntity], dt: float) -> None: ...
