from __future__ import annotations

from typing import Any

from sources.interns import PGExtern
from sources.interns.final_classes import JEInternWindowSettings
from sources.systems.color import JEColor

class JEWindow:
    def __init__(self, *, size: tuple[int, int], flags: int, fps: int, depth: int, display: int, vsync: int, title: str): ...
    def rename(self, title: str) -> None: ...
    @property
    def screen(self) -> PGExtern.Surface: ...
    @property
    def settings(self) -> JEInternWindowSettings: ...
    def fill(self, color: JEColor | tuple[int, int, int] | tuple[int, int, int, int]) -> None: ...
    def blit(self, source: PGExtern.Surface, dest: Any): ...
