from __future__ import annotations

from typing import Any, Self

class JEBool:
    def __init__(self, value: Any) -> None: ...
    def __bool__(self) -> bool: ...
    @property
    def data(self) -> bool: ...
