from __future__ import annotations

class JEClock:
    def __init__(self, fps: int) -> None: ...
    def update(self) -> None: ...
    @property
    def dt(self) -> float: ...
    @property
    def target_fps(self) -> int: ...
    @target_fps.setter
    def target_fps(self, value: int) -> None: ...
    @property
    def fps(self) -> float: ...
    def __float__(self) -> float: ...
