from __future__ import annotations

from typing import Iterator

class JEColor:
    def __init__(self, r: int, g: int, b: int, a: int) -> None: ...
    @property
    def r(self) -> int: ...
    @r.setter
    def r(self, r: int) -> None: ...
    @property
    def g(self) -> int: ...
    @g.setter
    def g(self, g: int) -> None: ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, b: int) -> None: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, a: int) -> None: ...
    @property
    def rgb(self) -> tuple[int, int, int]: ...
    @property
    def rgba(self) -> tuple[int, int, int, int]: ...
    def __iter__(self) -> Iterator[float]: ...
