from __future__ import annotations

from typing import TypeVar, Optional, Iterator

from sources.interns.base_classe import JEInternBaseClass
from sources.systems.bool import JEBool

_T = TypeVar("_T", bound=JEInternBaseClass)

class JEContainer:
    def __init__(self, allowed_type: type, allow_subclass: JEBool) -> None: ...
    def __setitem__(self, obj: _T) -> None: ...
    def add(self, obj: _T) -> None: ...
    def __getitem__(self, value: str | _T) -> _T: ...
    def get(self, *, name: Optional[str], jeid: Optional[str], instance: Optional[_T], _type: type) -> _T: ...
    def rm(self, *, name: Optional[str], jeid: Optional[str], instance: Optional[_T], _type: type) -> _T: ...
    def __iter__(self) -> Iterator[_T]: ...
    @property
    def data(self) -> _T: ...
