from __future__ import annotations

from jarengine.interns.base_classe import JEInternBaseClass
from jarengine.games.window import JEWindow
from jarengine.games.input import JEInput
from jarengine.events.manager import JEEventHandler
from jarengine.events.keyboard import JEKeyCode
from jarengine.events.mouse import JEMouseCode
from jarengine.entities.entity import JEEntity
from jarengine.systems.container import JEContainer
from jarengine.interns.high_classes import JEInternSystems
from jarengine.interns.final_classes import JEInternResources
from jarengine.systems.bool import JEBool
from jarengine.systems.clock import JEClock

class JEGame(JEInternBaseClass):
    def __init__(self, *, use_clock: JEBool = JEBool(0), use_input: JEBool = JEBool(0)): ...
    def set_window(self, window: JEWindow): ...
    @property
    def wdw(self) -> JEWindow: ...
    @property
    def input(self) -> JEInput: ...
    def is_key_down(self, key: JEKeyCode) -> bool: ...
    def is_mouse_down(self, button: JEMouseCode) -> bool: ...
    @property
    def clock(self) -> JEClock: ...
    @property
    def dt(self) -> float: ...
    @property
    def event(self) -> JEEventHandler: ...
    @property
    def is_open(self) -> JEBool: ...
    @property
    def ressource(self) -> JEInternResources: ...
    def refresh(self): ...
    def add_entity(self, entity: JEEntity): ...
    @property
    def entities(self) -> JEContainer[JEEntity]: ...
    def close(self): ...
    def add_system(self, system: JEInternSystems): ...
    @property
    def systems(self) -> JEContainer[JEInternSystems]: ...
    def update(self): ...
    def display(self): ...
