from __future__ import annotations

from jarengine.interns.base_classe import JEInternBaseClass
from jarengine.events.keyboard import JEKeyCode
from jarengine.events.mouse import JEMouseCode
from jarengine.systems.vector import JEVector2D

class JEInput(JEInternBaseClass):
    def __init__(self): ...
    def update(self): ...
    def is_key_down(self, key: JEKeyCode) -> bool: ...
    def is_mouse_down(self, button: JEMouseCode) -> bool: ...
    def mouse_pos(self) -> JEVector2D: ...
    def __call__(self, code: JEKeyCode | JEMouseCode) -> bool: ...
