from __future__ import annotations

from jarengine.interns.high_classes import JEInternEntityComponent
from jarengine.entities.entity import JEEntity
from jarengine.systems.container import JEContainer
from jarengine.games.window import JEWindow
from jarengine.games.game import JEGame
from jarengine.systems.bool import JEBool

class JEMovementSystem:
    def __init__(self, owner: JEGame): ...
    def accepts(self, components:  JEContainer[JEInternEntityComponent]) -> JEBool: ...
    def update(self, window: JEWindow, entity: JEEntity, entities: JEContainer[JEEntity], dt: float) -> None: ...

class JERenderSystem:
    def __init__(self, owner: JEGame): ...
    def accepts(self, components:  JEContainer[JEInternEntityComponent]) -> JEBool: ...
    def update(self, window: JEWindow, entity: JEEntity, entities: JEContainer[JEEntity], dt: float) -> None: ...

class JEAccelerationSystem:
    def __init__(self, owner: JEGame): ...
    def accepts(self, components:  JEContainer[JEInternEntityComponent]) -> JEBool: ...
    def update(self, window: JEWindow, entity: JEEntity, entities: JEContainer[JEEntity], dt: float) -> None: ...
