from __future__ import annotations

from jarengine.interns.high_classes import JEInternEntityComponent
from jarengine.resources.music import JEMusic
from jarengine.resources.sound import JESound
from jarengine.entities.entity import JEEntity
from jarengine.interns import PGExtern

class JEMusicComponent(JEInternEntityComponent):
    def __init__(self, owner: JEEntity, music: JEMusic):
        """
            JEMusicComponent

            Parameters:
                owner (JEEntity): owner of the component
                music (JEMusic): music resource
        """
        ...
    @property
    def music(self) -> JEMusic: ...
    @music.setter
    def music(self, font: JEMusic): ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, volume: float): ...
    def play(self, loop: int): ...
    def pause(self): ...
    def resume(self): ...
    def stop(self): ...
    def __call__(self) -> JEMusic: ...
    def copy(self, new_owner: JEEntity) -> JEMusicComponent: ...

class JESoundComponent(JEInternEntityComponent):
    def __init__(self, owner: JEEntity, sound: JESound):
        """
            JESoundComponent

            Parameters:
                owner (JEEntity): owner of the component
                sound (JESound): sound resource
        """
        ...
    @property
    def sound(self) -> JESound: ...
    @sound.setter
    def sound(self, font: JESound): ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, volume: float): ...
    def play(self, loop: int) -> PGExtern.mixer.Channel: ...
    def pause(self): ...
    def resume(self): ...
    def stop(self): ...
    def fadeout(self, milliseconds: int): ...
    def get_channel(self) -> PGExtern.mixer.Channel: ...
    def __call__(self) -> JEMusic: ...
    def copy(self, new_owner: JEEntity) -> JEMusicComponent: ...
