from __future__ import annotations

from jarengine.resources.music import JEMusic
from jarengine.resources.sound import JESound
from jarengine.entities.entity import JEEntity
from jarengine.interns import PGExtern

class JEMusicComponent:
    def __init__(self, owner: JEEntity, music: JEMusic) -> None: ...
    @property
    def music(self) -> JEMusic: ...
    @music.setter
    def music(self, font: JEMusic) -> None: ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, volume: float) -> None: ...
    def play(self, loop: int) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> None: ...
    def __call__(self) -> JEMusic: ...
    def copy(self, new_owner: JEEntity) -> JEMusicComponent: ...

class JESoundComponent:
    def __init__(self, owner: JEEntity, music: JESound) -> None: ...
    @property
    def sound(self) -> JESound: ...
    @sound.setter
    def sound(self, font: JESound) -> None: ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, volume: float) -> None: ...
    def play(self, loop: int) -> PGExtern.mixer.Channel: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> None: ...
    def fadeout(self, milliseconds: int): ...
    def get_channel(self) -> PGExtern.mixer.Channel: ...
    def __call__(self) -> JEMusic: ...
    def copy(self, new_owner: JEEntity) -> JEMusicComponent: ...
