from __future__ import annotations

from jarengine.entities.entity import JEEntity
from jarengine.systems.vector import JEVector2D

class JEAccelerationComponent:
    def __init__(self, owner: JEEntity, acceleration: JEVector2D | tuple[float, float]) -> None: ...
    @property
    def acceleration(self) -> JEVector2D: ...
    @acceleration.setter
    def acceleration(self, acceleration: JEVector2D | tuple[float, float]) -> None: ...
    def __call__(self) -> JEVector2D: ...
    def copy(self, new_owner: JEEntity) -> JEAccelerationComponent: ...

class JEMassComponent:
    def __init__(self, owner: JEEntity, mass: float) -> None: ...
    @property
    def mass(self) -> float: ...
    @mass.setter
    def mass(self, mass: float): ...
    def __call__(self) -> float: ...
    def copy(self, new_owner: JEEntity) -> JEMassComponent: ...
