from __future__ import annotations

from jarengine.resources.font import JEFont
from jarengine.entities.entity import JEEntity
from jarengine.resources.texture import JETexture
from jarengine.systems.color import JEColor
from jarengine.systems.bool import JEBool

class JEFontComponent:
    def __init__(self, owner: JEEntity, font: JEFont) -> None: ...
    @property
    def font(self) -> JEFont: ...
    @font.setter
    def font(self, font: JEFont) -> None: ...
    def __call__(self) -> JEFont: ...
    def copy(self, new_owner: JEEntity) -> JEFontComponent: ...

class JETextComponent:
    def __init__(self, owner: JEEntity, text: str) -> None: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, text: str) -> None: ...
    def __call__(self) -> str: ...
    def copy(self, new_owner: JEEntity) -> JETextComponent: ...

class JETextureComponent:
    def __init__(self, owner: JEEntity, texture: JETexture) -> None: ...
    @property
    def texture(self) -> JETexture: ...
    @texture.setter
    def texture(self, texture: JETexture) -> None: ...
    def __call__(self) -> JETexture: ...
    def copy(self, new_owner: JEEntity) -> JETextureComponent: ...

class JEColorComponent:
    def __init__(self, owner: JEEntity, color: JEColor | tuple[int, int, int] | tuple[int, int, int, int]) -> None: ...
    @property
    def color(self) -> JEColor: ...
    @color.setter
    def color(self, color: JEColor | tuple[int, int, int] | tuple[int, int, int, int]): ...
    def __call__(self) -> JEColor: ...
    def copy(self, new_owner: JEEntity) -> JEColorComponent: ...

class JEVisibilityComponent:
    def __init__(self, owner: JEEntity, visibility: JEBool): ...
    @property
    def visibility(self: JEBool): ...
    @visibility.setter
    def visibility(self, visibility: JEBool): ...
    def __call__(self: JEBool): ...
    def copy(self, new_owner: JEEntity) -> JEVisibilityComponent: ...

class JELayerComponent:
    def __init__(self, owner: JEEntity, layer: int): ...
    @property
    def layer(self: int): ...
    @layer.setter
    def layer(self, layer: int): ...
    def __call__(self: int): ...
    def copy(self, new_owner: JEEntity) -> JELayerComponent: ...

class JEFlipComponent:
    def __init__(self, owner: JEEntity, flip: tuple[JEBool, JEBool]): ...
    @property
    def flip(self) -> tuple[JEBool, JEBool]: ...
    @flip.setter
    def flip(self, flip: tuple[JEBool, JEBool]): ...
    def __call__(self: tuple[JEBool, JEBool]): ...
    def copy(self, new_owner: JEEntity) -> JEFlipComponent: ...
