from __future__ import annotations

from jarengine.interns.high_classes import JEInternEntityComponent
from jarengine.entities.entity import JEEntity
from jarengine.systems.container import JEContainer

class JEGroupComponent(JEInternEntityComponent):
    def __init__(self, owner: JEEntity) -> None: ...
    @property
    def group(self) -> JEContainer: ...
    @group.setter
    def group(self, entity: JEEntity) -> None: ...
    def group_remove(self, entity: JEEntity) -> None: ...
    def __call__(self) -> JEContainer: ...
    def copy(self, new_owner: JEEntity) -> JEGroupComponent: ...
