from __future__ import annotations

from jarengine.interns.low_classes import JEInternGraphicalObject
from jarengine.resources.font import JEFont
from jarengine.interns.high_classes import JEInternEntityComponent, JEInternOwnership
from jarengine.systems.container import JEContainer
from jarengine.systems.vector import JEVector2D
from jarengine.resources.texture import JETexture
from jarengine.systems.bool import JEBool
from jarengine.systems.color import JEColor

class JEEntity(JEInternGraphicalObject, JEInternOwnership):
    def __init__(self, *, name: str = "JEEntity") -> None: ...
    @property
    def components(self) -> JEContainer[JEInternEntityComponent]: ...
    def add_component(self, component: JEInternEntityComponent) -> None: ...
    def get(self, component: type) -> JEInternEntityComponent: ...
    def copy(self) -> JEEntity: ...


    ### COMPONENTS ###
    ## Graphics ##
    # Font #
    def set_font(self, font: JEFont) -> None: ...
    def get_font(self) -> JEFont: ...

    # Text #
    def set_text(self, text: str) -> None: ...
    def get_text(self) -> str: ...

    # Texture #
    def set_texture(self, texture: JETexture) -> None: ...
    def get_texture(self) -> JETexture: ...

    # Color #
    def set_color(self, color: JEColor | tuple[int, int, int] | tuple[int, int, int, int]) -> None: ...
    def update_color(self, *, r: int = 0, g: int = 0, b: int = 0, a: int = 0) -> None: ...
    def get_color(self) -> JEColor: ...

    # Outline #
    def set_outline_color(self, color: JEColor | tuple[int, int, int] | tuple[int, int, int, int]) -> None: ...
    def update_outline_color(self, *, r: int = 0, g: int = 0, b: int = 0, a: int = 0) -> None: ...
    def get_outline_color(self) -> JEColor: ...
    def set_outline_size(self, size: int) -> None: ...
    def update_outline_size(self, *, s: int = 0) -> None: ...
    def get_outline_size(self) -> int: ...

    # Visibility #
    def set_visibility(self, visibility: JEBool) -> None: ...
    def get_visibility(self) -> JEBool: ...

    # Layer #
    def set_layer(self, mass: int) -> None: ...
    def update_layer(self, *, l: int = 0) -> None: ...
    def get_layer(self) -> int: ...

    # Flip #
    def set_flip(self, flip: tuple[JEBool, JEBool]) -> None: ...
    def get_flip(self) -> tuple[JEBool, JEBool]: ...

    ## Audios ##
    # Music #
    def set_music(self, music) -> None: ...
    def play_music(self, loop: int = -1) -> None: ...
    def pause_music(self) -> None: ...
    def resume_music(self) -> None: ...
    def stop_music(self) -> None: ...
    def set_music_volume(self, volume: int) -> None: ...
    def get_music(self): ...

    # Sound #
    def set_sound(self, sound) -> None: ...
    def play_sound(self, loops: int = -1) -> None: ...
    def stop_sound(self) -> None: ...
    def pause_sound(self) -> None: ...
    def resume_sound(self) -> None: ...
    def fade_sound(self, milliseconds: int) -> None: ...
    def set_sound_volume(self, volume: int) -> None: ...
    def get_sound(self): ...


    ## Physics ##
    # Acceleration #
    def set_acceleration(self, acceleration: JEVector2D | tuple[float, float]) -> None: ...
    def update_acceleration(self, *, x: float = 0, y: float = 0) -> None: ...
    def get_acceleration(self) -> JEVector2D: ...

    # Mass #
    def set_mass(self, mass: float) -> None: ...
    def update_mass(self, *, m: float = 0) -> None: ...
    def get_mass(self) -> float: ...


    ## Transforms ##
    # Position #
    def set_position(self, position: JEVector2D | tuple[float, float]) -> None: ...
    def update_position(self, *, x: float = 0, y: float = 0) -> None: ...
    def get_position(self) -> JEVector2D: ...

    # Velocity #
    def set_velocity(self, velocity: JEVector2D | tuple[float, float]) -> None: ...
    def update_velocity(self, *, x: float = 0, y: float = 0) -> None: ...
    def get_velocity(self) -> JEVector2D: ...

    # Size #
    def set_size(self, size: JEVector2D | tuple[float, float]) -> None: ...
    def update_size(self, *, x: float = 0, y: float = 0) -> None: ...
    def get_size(self) -> JEVector2D: ...

    # Rotation #
    def set_rotation(self, rotation: float) -> None: ...
    def update_rotation(self, *, r: float = 0) -> None: ...
    def get_rotation(self) -> float: ...


    ## Others ##
    # Group #
    def group_add(self, entity: JEEntity) -> None: ...
    def group_remove(self, entity: JEEntity) -> None: ...
    def get_group(self) -> JEContainer[JEEntity]: ...
